name: Xcode - Build and Analyze

on: workflow_dispatch

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
              - name: Build iOS Action
                uses: sparkfabrik/ios-build-action@v2.3.2
            
